name: Testing

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - uses: php-actions/phpstan@v3
    - uses: php-actions/phpunit@v3
      with:
        php_extensions: xdebug
        coverage_clover: coverage/clover.xml
